2 HomeWork
js-tasks-ru/js-20220513_alubochkin pull request #2
Opened 2022-05-18 22:54 UTC by alubochkin

2022-05-18 22:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-18 23:04 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-19 10:30 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return result.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-05-19 10:30 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.spec.js
> +import { sortStrings } from "./index.js";
не меняйте файлы тестов

2022-05-19 10:31 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
>  export const pick = (obj, ...fields) => {
👍 good

2022-05-19 10:31 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
>  export const omit = (obj, ...fields) => {
👍 good

2022-05-19 10:32 UTC, dosandk requested changes
Решение `sortStrings` следует поправить согласно комментариев

2022-05-19 17:51 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-19 18:07 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-20 13:04 UTC, dosandk approved these changes
👍 good

2022-05-20 13:04 UTC, merged